"""
Sentinel Agent — Background Portfolio Protection.

Runs on a configurable interval (default: every 5 minutes for active users)
and monitors tracked wallets, token holdings, and approvals for emerging risks.

ANALYSIS ONLY — never executes transactions or moves funds.

Monitors:
  - Token score drops (held token becomes risky)
  - New risky approvals granted by user wallets
  - Whale dumps in tokens the user holds
  - Protocol exploits for protocols/tokens in user portfolio
  - Anomalous on-chain activity in held tokens
"""

import asyncio
import logging
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional

from src.alerts.orchestrator import AlertOrchestrator
from src.alerts.store import InMemoryAlertStore
from src.api.routes.alerts import ALERT_STORE_KEY
from src.config import settings

logger = logging.getLogger(__name__)

# How often to check each user (seconds). Active users checked more frequently.
ACTIVE_CHECK_INTERVAL = 300     # 5 minutes
INACTIVE_CHECK_INTERVAL = 3600  # 1 hour

# Risk score drop threshold that triggers an alert
RISK_SCORE_DROP_THRESHOLD = 15   # Alert if score drops by 15+ points
RISK_SCORE_DANGER_FLOOR = 35     # Alert if score falls below this


@dataclass
class SentinelAlert:
    """An alert generated by the sentinel."""
    alert_type: str          # token_risk_drop | new_risky_approval | whale_dump | protocol_exploit
    severity: str            # CRITICAL | HIGH | MEDIUM | LOW
    title: str
    body: str
    token_address: Optional[str] = None
    wallet_address: Optional[str] = None
    chain: Optional[str] = None
    data: Dict[str, Any] = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)


AlertHandler = Callable[[SentinelAlert], None]


class SentinelAgent:
    """
    Background sentinel that monitors user portfolios for emerging risks.

    Usage:
        agent = SentinelAgent()
        agent.add_alert_handler(my_handler)
        agent.watch_wallet("0xabc...", chains=["ethereum"])
        await agent.start()          # runs until stopped
        await agent.stop()
    """

    def __init__(self, check_interval: int = ACTIVE_CHECK_INTERVAL):
        self._check_interval = check_interval
        self._running = False
        self._task: Optional[asyncio.Task] = None
        self._alert_handlers: List[AlertHandler] = []

        # Watched wallets: {wallet_address: {chains: [...], last_checked: float}}
        self._watched_wallets: Dict[str, Dict[str, Any]] = {}

        # Score history for held tokens: {token_address: previous_score}
        self._score_history: Dict[str, float] = {}

        # Known approval snapshots: {wallet: set of (token, spender) tuples}
        self._approval_snapshots: Dict[str, set] = {}

        # Lazy imports to avoid circular dependencies
        self._shield_scanner = None
        self._rekt_db = None

    # ------------------------------------------------------------------
    # Public control API
    # ------------------------------------------------------------------

    def watch_wallet(
        self,
        wallet: str,
        chains: Optional[List[str]] = None,
        label: Optional[str] = None,
    ):
        """Add a wallet to the sentinel's watch list."""
        self._watched_wallets[wallet.lower()] = {
            "chains": chains or ["ethereum", "bsc", "polygon", "arbitrum", "base"],
            "label": label or wallet[:8] + "...",
            "last_checked": 0.0,
        }
        logger.info(f"Sentinel: watching wallet {wallet[:8]}...")

    def unwatch_wallet(self, wallet: str):
        """Remove a wallet from the watch list."""
        self._watched_wallets.pop(wallet.lower(), None)

    def add_alert_handler(self, handler: AlertHandler):
        """Register a callback to receive alerts."""
        self._alert_handlers.append(handler)

    def _emit(self, alert: SentinelAlert):
        """Dispatch alert to all registered handlers."""
        logger.warning(
            f"[SENTINEL ALERT] {alert.severity} | {alert.alert_type} | {alert.title}"
        )
        for handler in self._alert_handlers:
            try:
                handler(alert)
            except Exception as e:
                logger.error(f"Alert handler error: {e}")

    # ------------------------------------------------------------------
    # Monitoring loops
    # ------------------------------------------------------------------

    async def _check_wallet_approvals(self, wallet: str, info: Dict[str, Any]):
        """
        Check for new high-risk approvals since last scan.
        Emits alerts for HIGH-risk approvals the sentinel hasn't seen before.
        """
        if self._shield_scanner is None:
            from src.shield.approval_scanner import ApprovalScanner
            self._shield_scanner = ApprovalScanner()

        from src.chains.base import ChainType
        chain_map = {
            "ethereum": ChainType.ETHEREUM, "bsc": ChainType.BSC,
            "polygon": ChainType.POLYGON, "arbitrum": ChainType.ARBITRUM,
            "base": ChainType.BASE, "optimism": ChainType.OPTIMISM,
            "avalanche": ChainType.AVALANCHE,
        }
        chains = [chain_map[c] for c in info.get("chains", []) if c in chain_map]

        try:
            approvals = await self._shield_scanner.scan_wallet(wallet, chains=chains)
        except Exception as e:
            logger.warning(f"Sentinel approval scan failed for {wallet}: {e}")
            return

        snapshot_key = wallet.lower()
        seen = self._approval_snapshots.get(snapshot_key, set())
        new_seen = set()

        for approval in approvals:
            key = (approval.get("token_address", ""), approval.get("spender_address", ""))
            new_seen.add(key)

            # Only alert for HIGH risk approvals we haven't seen before
            if key not in seen and approval.get("risk_level") == "HIGH":
                spender = approval.get("spender_name") or approval["spender_address"][:10] + "..."
                self._emit(SentinelAlert(
                    alert_type="new_risky_approval",
                    severity="HIGH",
                    title=f"High-Risk Approval Detected",
                    body=(
                        f"Wallet {info.get('label')} granted a HIGH-RISK token approval "
                        f"to {spender} on {approval.get('chain', 'unknown chain')}. "
                        f"Risk score: {approval.get('risk_score', '?')}/100. "
                        f"Allowance: {approval.get('allowance', '?')}. "
                        "Consider revoking this approval via the Shield tab."
                    ),
                    wallet_address=wallet,
                    chain=approval.get("chain"),
                    data=approval,
                ))

        self._approval_snapshots[snapshot_key] = new_seen

    async def _check_rekt_news(self):
        """
        Check the REKT database for new incidents affecting watched protocols.
        Emits CRITICAL alerts for new exploits.
        """
        if self._rekt_db is None:
            from src.intel.rekt_database import RektDatabase
            self._rekt_db = RektDatabase()

        try:
            # Fetch incidents from last 7 days
            from datetime import datetime, timedelta
            week_ago = (datetime.utcnow() - timedelta(days=7)).strftime("%Y-%m-%d")
            incidents = await self._rekt_db.get_incidents(limit=20)
            recent = [i for i in incidents if (i.get("date") or "") >= week_ago]
        except Exception as e:
            logger.warning(f"Sentinel REKT check failed: {e}")
            return

        for incident in recent:
            # In a full implementation we'd cross-reference incident protocol
            # against user's portfolio. For now emit for CRITICAL incidents.
            if incident.get("severity") == "CRITICAL":
                self._emit(SentinelAlert(
                    alert_type="protocol_exploit",
                    severity="CRITICAL",
                    title=f"Active Exploit: {incident.get('name', 'Unknown Protocol')}",
                    body=(
                        f"{incident.get('name')} was exploited for "
                        f"${incident.get('amount_usd', 0):,.0f}. "
                        f"Attack type: {incident.get('attack_type', 'unknown')}. "
                        f"{incident.get('description', '')[:200]}"
                    ),
                    chain=", ".join(incident.get("chains") or []),
                    data=incident,
                ))

    async def _check_cycle(self):
        """Run one full check cycle across all watched wallets."""
        now = time.time()

        for wallet, info in list(self._watched_wallets.items()):
            last = info.get("last_checked", 0)
            if (now - last) < self._check_interval:
                continue

            logger.debug(f"Sentinel checking wallet {wallet[:8]}...")
            info["last_checked"] = now

            # Run all checks concurrently per wallet
            await asyncio.gather(
                self._check_wallet_approvals(wallet, info),
                return_exceptions=True,
            )

        # Global checks (not per-wallet)
        await self._check_rekt_news()

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def _run_loop(self):
        """Main sentinel loop."""
        logger.info(f"Sentinel agent started (interval: {self._check_interval}s)")
        while self._running:
            try:
                await self._check_cycle()
            except Exception as e:
                logger.error(f"Sentinel cycle error: {e}")
            await asyncio.sleep(60)  # sleep 60s between cycle attempts
        logger.info("Sentinel agent stopped")

    async def start(self):
        """Start the sentinel background loop."""
        if self._running:
            return
        self._running = True
        self._task = asyncio.create_task(self._run_loop())

    async def stop(self):
        """Stop the sentinel and clean up resources."""
        self._running = False
        if self._task:
            self._task.cancel()
            try:
                await self._task
            except asyncio.CancelledError:
                pass
        if self._shield_scanner:
            await self._shield_scanner.close()
        if self._rekt_db:
            await self._rekt_db.close()
        logger.info("Sentinel agent shut down cleanly")


# Module-level singleton for app-wide use
_sentinel: Optional[SentinelAgent] = None
_alert_bridge_registered = False


def get_sentinel() -> SentinelAgent:
    """Get or create the global sentinel instance."""
    global _sentinel
    if _sentinel is None:
        _sentinel = SentinelAgent()
    return _sentinel


def create_alert_orchestrator(store: InMemoryAlertStore | None = None) -> AlertOrchestrator:
    alert_store = store or InMemoryAlertStore()
    return AlertOrchestrator(
        store=alert_store,
        dedupe_window_seconds=settings.alert_dedupe_window_seconds,
    )


def _to_orchestrator_event(alert: SentinelAlert) -> dict[str, str]:
    subject_id = alert.token_address or alert.wallet_address or alert.chain or "global"
    return {
        "user_id": alert.wallet_address or "sentinel",
        "rule_id": alert.alert_type,
        "subject_id": subject_id,
        "severity": alert.severity.lower(),
        "kind": alert.alert_type,
    }


async def start_sentinel(app):
    """aiohttp startup hook."""
    global _alert_bridge_registered
    sentinel = get_sentinel()

    if app is not None and ALERT_STORE_KEY in app and not _alert_bridge_registered:
        orchestrator = create_alert_orchestrator(store=app[ALERT_STORE_KEY])

        def _bridge_handler(alert: SentinelAlert) -> None:
            orchestrator.ingest(_to_orchestrator_event(alert))

        sentinel.add_alert_handler(_bridge_handler)
        _alert_bridge_registered = True

    await sentinel.start()
    logger.info("Sentinel agent registered")


async def stop_sentinel(app):
    """aiohttp cleanup hook."""
    if _sentinel:
        await _sentinel.stop()
